export const SET_CONTACTS = "SET_CONTACTS";
export const SET_ADD_CONTACT = "SET_ADD_CONTACT";
export const RESET_CONTACT = "RESET_CONTACT";
export const CREATE_CONTACT = "CREATE_CONTACT";
export const UPDATE_CONTACT = "UPDATE_CONTACT";
export const DELETE_CONTACT = "DELETE_CONTACT";
export const ADD_MODEL_STATUS = "ADD_MODEL_STATUS";
export const EDIT_MODEL_STATUS = "EDIT_MODEL_STATUS";
